export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL";

export const ALL_BASIC_INFO_REQUEST = "ALL_BASIC_INFO_REQUEST";
export const ALL_BASIC_INFO_SUCCESS = "ALL_BASIC_INFO_SUCCESS";
export const ALL_BASIC_INFO_FAIL = "ALL_BASIC_INFO_FAIL";

export const NEW_PROJECT_REQUEST = "NEW_PROJECT_REQUEST";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PROJECT_RESET = "NEW_PROJECT_RESET";
export const NEW_PROJECT_FAIL = "NEW_PROJECT_FAIL";

export const NEW_BASIC_INFO_REQUEST = "NEW_BASIC_INFO_REQUEST";
export const NEW_BASIC_INFO_SUCCESS = "NEW_BASIC_INFO_SUCCESS";
export const NEW_BASIC_INFO_RESET = "NEW_BASIC_INFO_RESET";
export const NEW_BASIC_INFO_FAIL = "NEW_BASIC_INFO_FAIL";

export const UPDATE_BASIC_INFO_REQUEST = "UPDATE_BASIC_INFO_REQUEST";
export const UPDATE_BASIC_INFO_SUCCESS = "UPDATE_BASIC_INFO_SUCCESS";
export const UPDATE_BASIC_INFO_RESET = "UPDATE_BASIC_INFO_RESET";
export const UPDATE_BASIC_INFO_FAIL = "UPDATE_BASIC_INFO_FAIL";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_RESET = "UPDATE_PROJECT_RESET";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_RESET = "DELETE_PROJECT_RESET";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const PROJECT_BASIC_INFO_REQUEST = "PROJECT_BASIC_INFO_REQUEST";
export const PROJECT_BASIC_INFO_SUCCESS = "PROJECT_BASIC_INFO_SUCCESS";
export const PROJECT_BASIC_INFO_FAIL = "PROJECT_BASIC_INFO_FAIL";


export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const DELETE_BASIC_INFO_REQUEST = "DELETE_BASIC_INFO_REQUEST";
export const DELETE_BASIC_INFO_SUCCESS = "DELETE_BASIC_INFO_SUCCESS";
export const DELETE_BASIC_INFO_RESET = "DELETE_BASIC_INFO_RESET";
export const DELETE_BASIC_INFO_FAIL = "DELETE_BASIC_INFO_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";