export const ALL_PUB_DOC_REQUEST = "ALL_PUB_DOC_REQUEST";
export const ALL_PUB_DOC_SUCCESS = "ALL_PUB_DOC_SUCCESS";
export const ALL_PUB_DOC_FAIL = "ALL_PUB_DOC_FAIL";


export const NEW_PUB_DOC_REQUEST = "NEW_PUB_DOC_REQUEST";
export const NEW_PUB_DOC_SUCCESS = "NEW_PUB_DOC_SUCCESS";
export const NEW_PUB_DOC_RESET = "NEW_PUB_DOC_RESET";
export const NEW_PUB_DOC_FAIL = "NEW_PUB_DOC_FAIL";

export const DELETE_PUB_DOC_REQUEST = "DELETE_PUB_DOC_REQUEST";
export const DELETE_PUB_DOC_SUCCESS = "DELETE_PUB_DOC_SUCCESS";
export const DELETE_PUB_DOC_RESET = "DELETE_PUB_DOC_RESET";
export const DELETE_PUB_DOC_FAIL = "DELETE_PUB_DOC_FAIL";

export const PUB_DOC_DETAILS_REQUEST = "PUB_DOC_DETAILS_REQUEST";
export const PUB_DOC_DETAILS_SUCCESS = "PUB_DOC_DETAILS_SUCCESS";
export const PUB_DOC_DETAILS_FAIL = "PUB_DOC_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";