export const ALL_TXT_FILE_REQUEST = "ALL_TXT_FILE_REQUEST";
export const ALL_TXT_FILE_SUCCESS = "ALL_TXT_FILE_SUCCESS";
export const ALL_TXT_FILE_FAIL = "ALL_TXT_FILE_FAIL";

export const NEW_TXT_FILE_REQUEST = "NEW_TXT_FILE_REQUEST";
export const NEW_TXT_FILE_SUCCESS = "NEW_TXT_FILE_SUCCESS";
export const NEW_TXT_FILE_RESET = "NEW_TXT_FILE_RESET";
export const NEW_TXT_FILE_FAIL = "NEW_TXT_FILE_FAIL";

export const UPDATE_TXT_FILE_REQUEST = "UPDATE_TXT_FILE_REQUEST";
export const UPDATE_TXT_FILE_SUCCESS = "UPDATE_TXT_FILE_SUCCESS";
export const UPDATE_TXT_FILE_RESET = "UPDATE_TXT_FILE_RESET";
export const UPDATE_TXT_FILE_FAIL = "UPDATE_TXT_FILE_FAIL";

export const DELETE_TXT_FILE_REQUEST = "DELETE_TXT_FILE_REQUEST";
export const DELETE_TXT_FILE_SUCCESS = "DELETE_TXT_FILE_SUCCESS";
export const DELETE_TXT_FILE_RESET = "DELETE_TXT_FILE_RESET";
export const DELETE_TXT_FILE_FAIL = "DELETE_TXT_FILE_FAIL";

export const TXT_FILE_DETAIL_REQUEST = "TXT_FILE_DETAIL_REQUEST";
export const TXT_FILE_DETAIL_SUCCESS = "TXT_FILE_DETAIL_SUCCESS";
export const TXT_FILE_DETAIL_RESET = "TXT_FILE_DETAIL_RESET";
export const TXT_FILE_DETAIL_FAIL = "TXT_FILE_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";